/* STRIDE — catálogo de produtos (dados estáticos de demonstração) */

const CATEGORIES = [
  { slug: "camisetas", name: "Camisetas", image: "stride-cat-tee" },
  { slug: "moletons", name: "Moletons & Jaquetas", image: "stride-cat-hoodie" },
  { slug: "calcas", name: "Calças & Shorts", image: "stride-cat-pants" },
  { slug: "tenis", name: "Tênis", image: "stride-cat-shoe" },
  { slug: "acessorios", name: "Acessórios", image: "stride-cat-acc" },
];

const SIZES_ROUPA = ["P", "M", "G", "GG"];
const SIZES_TENIS = ["38", "39", "40", "41", "42", "43", "44"];
const SIZES_UNICO = ["Único"];

const CORES_PADRAO = [
  { name: "Preto", hex: "#111111" },
  { name: "Branco", hex: "#f5f5f3" },
  { name: "Cinza Mescla", hex: "#9a9a92" },
];

const CORES_VOLT = [
  { name: "Preto/Volt", hex: "#111111" },
  { name: "Branco/Volt", hex: "#f5f5f3" },
];

const PRODUCTS = [
  {
    id: 1,
    name: "Camiseta Oversized Essential",
    cat: "camisetas",
    price: 129.9,
    seed: "stride-tee-1",
    badge: "Mais Vendido",
    featured: true,
    rating: 4.8,
    reviews: 214,
    sizes: SIZES_ROUPA,
    colors: CORES_PADRAO,
    desc: "Corte oversized, malha 100% algodão penteado e caimento solto pra usar em qualquer situação — do treino à rua, sem esforço.",
  },
  {
    id: 2,
    name: "Camiseta Performance Secagem Rápida",
    cat: "camisetas",
    price: 149.9,
    seed: "stride-tee-2",
    badge: "Novo",
    featured: true,
    rating: 4.7,
    reviews: 98,
    sizes: SIZES_ROUPA,
    colors: CORES_VOLT,
    desc: "Tecido tecnológico com secagem rápida e tratamento antiodor. Feita pra acompanhar seu treino do aquecimento ao último rep.",
  },
  {
    id: 3,
    name: "Regata Training Básica",
    cat: "camisetas",
    price: 99.9,
    seed: "stride-tee-3",
    rating: 4.5,
    reviews: 63,
    sizes: SIZES_ROUPA,
    colors: CORES_PADRAO,
    desc: "Regata leve em malha canelada, cavas amplas e caimento reto. Essencial de treino que também funciona no dia a dia.",
  },
  {
    id: 4,
    name: "Camiseta Estampada Street Logo",
    cat: "camisetas",
    price: 139.9,
    seed: "stride-tee-4",
    badge: "Novo",
    featured: true,
    rating: 4.9,
    reviews: 156,
    sizes: SIZES_ROUPA,
    colors: CORES_PADRAO,
    desc: "Estampa gráfica na frente e nas costas, algodão pesado 220g/m² pra durar e manter a forma lavagem após lavagem.",
  },
  {
    id: 5,
    name: "Moletom Canguru Urban",
    cat: "moletons",
    price: 219.9,
    seed: "stride-hoodie-1",
    badge: "Mais Vendido",
    featured: true,
    rating: 4.8,
    reviews: 187,
    sizes: SIZES_ROUPA,
    colors: CORES_PADRAO,
    desc: "Moletom com capuz forrado, bolso canguru e punhos reforçados. Peso ideal pra estação fria sem pesar no visual.",
  },
  {
    id: 6,
    name: "Moletom Careca Heavyweight",
    cat: "moletons",
    price: 199.9,
    seed: "stride-hoodie-2",
    rating: 4.6,
    reviews: 74,
    sizes: SIZES_ROUPA,
    colors: CORES_PADRAO,
    desc: "Moletom careca em fleece encorpado 400g, gola careca reforçada e corte reto minimalista.",
  },
  {
    id: 7,
    name: "Jaqueta Corta-Vento Storm Runner",
    cat: "moletons",
    price: 259.9,
    seed: "stride-jacket-1",
    badge: "Edição Limitada",
    featured: true,
    rating: 4.9,
    reviews: 41,
    sizes: SIZES_ROUPA,
    colors: CORES_VOLT,
    desc: "Corta-vento leve com forro em mesh, capuz ajustável e bolso frontal com zíper. Proteção sem abrir mão da mobilidade.",
  },
  {
    id: 8,
    name: "Calça Jogger Performance",
    cat: "calcas",
    price: 189.9,
    seed: "stride-pants-1",
    rating: 4.7,
    reviews: 132,
    sizes: SIZES_ROUPA,
    colors: CORES_PADRAO,
    desc: "Jogger com elastano, punho no tornozelo e bolsos com zíper. Liberdade de movimento pra treinar ou circular na cidade.",
  },
  {
    id: 9,
    name: "Shorts Training Flex",
    cat: "calcas",
    price: 119.9,
    seed: "stride-shorts-1",
    badge: "Novo",
    featured: true,
    rating: 4.6,
    reviews: 58,
    sizes: SIZES_ROUPA,
    colors: CORES_PADRAO,
    desc: "Shorts leve com tela interna, cintura elástica com cordão e tecido com secagem rápida pra qualquer treino.",
  },
  {
    id: 10,
    name: "Calça Cargo Street",
    cat: "calcas",
    price: 229.9,
    seed: "stride-pants-2",
    rating: 4.5,
    reviews: 47,
    sizes: SIZES_ROUPA,
    colors: CORES_PADRAO,
    desc: "Silhueta ampla com bolsos cargo funcionais e cadarço ajustável na barra. Streetwear com pegada utilitária.",
  },
  {
    id: 11,
    name: "Tênis Runner Pro X",
    cat: "tenis",
    price: 349.9,
    seed: "stride-shoe-1",
    badge: "Mais Vendido",
    featured: true,
    rating: 4.9,
    reviews: 302,
    sizes: SIZES_TENIS,
    colors: CORES_VOLT,
    desc: "Entressola com amortecimento responsivo e cabedal em engineered mesh respirável. Feito pra ritmo e distância.",
  },
  {
    id: 12,
    name: "Tênis Street Classic",
    cat: "tenis",
    price: 299.9,
    seed: "stride-shoe-2",
    rating: 4.7,
    reviews: 168,
    sizes: SIZES_TENIS,
    colors: CORES_PADRAO,
    desc: "Silhueta baixa clássica em couro sintético, solado em borracha vulcanizada. Do skate pro dia a dia.",
  },
  {
    id: 13,
    name: "Tênis Court Low",
    cat: "tenis",
    price: 279.9,
    seed: "stride-shoe-3",
    badge: "Novo",
    featured: true,
    rating: 4.6,
    reviews: 89,
    sizes: SIZES_TENIS,
    colors: CORES_PADRAO,
    desc: "Inspirado nas quadras, cabedal em couro premium e entressola leve em EVA. Conforto o dia inteiro.",
  },
  {
    id: 14,
    name: "Tênis Trail Grip",
    cat: "tenis",
    price: 369.9,
    seed: "stride-shoe-4",
    badge: "Edição Limitada",
    rating: 4.8,
    reviews: 36,
    sizes: SIZES_TENIS,
    colors: CORES_PADRAO,
    desc: "Solado com tração agressiva multiterreno e cabedal resistente à água. Pra sair do asfalto sem medo.",
  },
  {
    id: 15,
    name: "Boné Aba Curva Logo",
    cat: "acessorios",
    price: 89.9,
    seed: "stride-cap-1",
    rating: 4.7,
    reviews: 121,
    sizes: SIZES_UNICO,
    colors: CORES_PADRAO,
    desc: "Boné estruturado com aba curva, fecho ajustável traseiro e bordado 3D na frente.",
  },
  {
    id: 16,
    name: "Meia Cano Alto Kit 3",
    cat: "acessorios",
    price: 49.9,
    seed: "stride-socks-1",
    rating: 4.5,
    reviews: 77,
    sizes: SIZES_UNICO,
    colors: CORES_PADRAO,
    desc: "Kit com 3 pares em algodão canelado, solado reforçado e faixa de compressão leve no arco do pé.",
  },
  {
    id: 17,
    name: "Mochila Sport Pack",
    cat: "acessorios",
    price: 179.9,
    seed: "stride-bag-1",
    badge: "Novo",
    featured: true,
    rating: 4.8,
    reviews: 64,
    sizes: SIZES_UNICO,
    colors: CORES_PADRAO,
    desc: "Compartimento acolchoado pra notebook, bolso térmico lateral e tecido resistente à água.",
  },
  {
    id: 18,
    name: "Pochete Utility",
    cat: "acessorios",
    price: 79.9,
    seed: "stride-bag-2",
    rating: 4.4,
    reviews: 29,
    sizes: SIZES_UNICO,
    colors: CORES_PADRAO,
    desc: "Pochete compacta com dois compartimentos e alça regulável. Praticidade pra levar o essencial.",
  },
];

function getProductById(id) {
  return PRODUCTS.find((p) => p.id === Number(id));
}

function getCategoryBySlug(slug) {
  return CATEGORIES.find((c) => c.slug === slug);
}

function formatPrice(value) {
  return "R$ " + value.toFixed(2).replace(".", ",");
}

function productImage(seed, w, h) {
  return "https://picsum.photos/seed/" + seed + "/" + w + "/" + h;
}
